name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest-full # Or your preferred runner image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: anki-autocard
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: Push to gitea 
        uses: redhat-actions/push-to-registry@v2
        with:
          image: anki-autocard
          tags: latest 
          registry: 10.8.0.1:4443
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWORD }}
