name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Or your preferred runner image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: redhat-actions/podman-login@v1 # Example for a generic registry
        with:
          username: ${{  secrets.USERNAME  }}
          password: ${{  secrets.PASSWORD  }}
          registry: 10.8.0.1:4443 # Replace with your registry

      - name: Build image with Podman
        run: |
          podman build -t 10.8.0.1:4443/e74b/anki-autocard:latest .

      - name: Push image to Registry
        run: |
          podman push 10.8.0.1:4443/e74b/anki-autocard:latest
